-- MySQL Script generated by MySQL Workbench
-- Tue Feb  4 13:37:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema P5OC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema P5OC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `P5OC` DEFAULT CHARACTER SET utf8 ;
USE `P5OC` ;

-- -----------------------------------------------------
-- Table `P5OC`.`food_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5OC`.`food_item` (
  `id_openfoodfacts` BIGINT(20) UNSIGNED NOT NULL,
  `food_name` VARCHAR(100) NOT NULL,
  `food_brand` VARCHAR(50) NOT NULL,
  `food_generic_name` VARCHAR(100) NULL,
  `nutriscore` CHAR(1) NOT NULL,
  `nova_grade` SMALLINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_openfoodfacts`),
  FULLTEXT INDEX `name_fulltext` (`food_name`) VISIBLE,
  UNIQUE INDEX `id_openfoodfacts_UNIQUE` (`id_openfoodfacts` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5OC`.`nutrition_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5OC`.`nutrition_score` (
  `id_nutrition_score` INT NOT NULL AUTO_INCREMENT,
  `nutrition_score_name` VARCHAR(10) NOT NULL,
  `nutrition_score_rating` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_nutrition_score`),
  UNIQUE INDEX `id_nutrition_score_UNIQUE` (`id_nutrition_score` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5OC`.`food_item_nutrition_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5OC`.`food_item_nutrition_score` (
  `food_item_id_openfoodfacts` BIGINT(20) UNSIGNED NOT NULL,
  `id_nutrition_score` INT NOT NULL,
  PRIMARY KEY (`food_item_id_openfoodfacts`, `id_nutrition_score`),
  INDEX `FK_id_nutrition_score_idx` (`id_nutrition_score` ASC) VISIBLE,
  UNIQUE INDEX `food_item_id_openfoodfacts_UNIQUE` (`food_item_id_openfoodfacts` ASC) VISIBLE,
  CONSTRAINT `food_item_id_openfoodfacts_FK1`
    FOREIGN KEY (`food_item_id_openfoodfacts`)
    REFERENCES `P5OC`.`food_item` (`id_openfoodfacts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_nutrition_score_FK1`
    FOREIGN KEY (`id_nutrition_score`)
    REFERENCES `P5OC`.`nutrition_score` (`id_nutrition_score`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5OC`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5OC`.`store` (
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  FULLTEXT INDEX `name_fulltext` (`name`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5OC`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5OC`.`category` (
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  FULLTEXT INDEX `name_fulltext` (`name`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5OC`.`food_item_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5OC`.`food_item_store` (
  `food_item_id_openfoodfacts` BIGINT(20) UNSIGNED NOT NULL,
  `store_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`food_item_id_openfoodfacts`, `store_name`),
  INDEX `store_name_idx` (`store_name` ASC) VISIBLE,
  CONSTRAINT `food_item_id_openfoodfacts_FK3`
    FOREIGN KEY (`food_item_id_openfoodfacts`)
    REFERENCES `P5OC`.`food_item` (`id_openfoodfacts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `store_name_FK1`
    FOREIGN KEY (`store_name`)
    REFERENCES `P5OC`.`store` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5OC`.`food_item_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5OC`.`food_item_category` (
  `food_item_id_openfoodfacts` BIGINT(20) UNSIGNED NOT NULL,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`food_item_id_openfoodfacts`, `category_name`),
  CONSTRAINT `food_item_id_openfoodfacts_FK2`
    FOREIGN KEY (`food_item_id_openfoodfacts`)
    REFERENCES `P5OC`.`food_item` (`id_openfoodfacts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `category_name_FK1`
    FOREIGN KEY (`category_name`)
    REFERENCES `P5OC`.`category` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5OC`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5OC`.`favoris` (
  `favori_id_openfoodfacts` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`favori_id_openfoodfacts`),
  UNIQUE INDEX `idfavoris_UNIQUE` (`favori_id_openfoodfacts` ASC) VISIBLE,
  CONSTRAINT `fk_id_openfoodfacts`
    FOREIGN KEY (`favori_id_openfoodfacts`)
    REFERENCES `P5OC`.`food_item` (`id_openfoodfacts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE USER 'program' IDENTIFIED BY 'program';

GRANT SELECT, INSERT, TRIGGER ON TABLE `P5OC`.* TO 'program';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `P5OC`.* TO 'program';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
